#pragma once


#define VITA_SCREEN_W 960
#define VITA_SCREEN_H 544

enum ui_key_code {
    UI_KEY_CODE_VITA_DPAD_LEFT,
    UI_KEY_CODE_VITA_DPAD_RIGHT,
    UI_KEY_CODE_VITA_DPAD_UP,
    UI_KEY_CODE_VITA_DPAD_DOWN,
    UI_KEY_CODE_VITA_ACTION_SQUARE,
    UI_KEY_CODE_VITA_ACTION_CIRCLE,
    UI_KEY_CODE_VITA_ACTION_TRIANGLE,
    UI_KEY_CODE_VITA_ACTION_CROSS,
    UI_KEY_CODE_VITA_L1,
    UI_KEY_CODE_VITA_R1,
    UI_KEY_CODE_VITA_START,
    UI_KEY_CODE_VITA_SELECT,
    UI_KEY_CODE_VITA_END,
};

enum ui_key_state {
    UI_KEY_STATE_DOWN,
    UI_KEY_STATE_UP,
};
